### ISSUE TITLE
Senha de acesso

### ISSUE THREAD

**Issue by renatorsti** [silvenga-docker/acronis-backup#1]
Opa! 
Fiz a instalação porem não localizei a senha para acessar o console da ferramenta, poderia me informar o usuario e a senha para acesso?

**Comment by Silvenga** [comment]
Unfortunately, this image doesn't quite work. There wasn't a way that I could find to get Acronis to exit cleanly. So it would often corput the sqlite database that Aconis uses internally.

So I ended up having a separate VM for Acrois, but never removed this image. In theory, this image should work with an external database.

Auth by default would use PAM, so you would need to add a new user to this image.

**Comment by Silvenga** [comment]
Closing for now.
